[package]
name = "winit"
version = "0.5.11"
authors = ["The winit contributors, Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Cross-platform window creation library."
keywords = ["windowing"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/tomaka/winit"
documentation = "https://docs.rs/winit"

[dependencies]
lazy_static = "0.2.2"
libc = "0.2"
shared_library = "0.1.5"

log = "0.3"
simplelog = "0.4.2"
log-panics = "1.1.0"

[target.'cfg(target_os = "android")'.dependencies.android_glue]
version = "0.2"

[target.'cfg(target_os = "ios")'.dependencies]
objc = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"
cgl = "0.1"
cocoa = "=0.5.2"
core-foundation = "0.2"
core-graphics = "0.4"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = "0.2"
shell32-sys = "0.1"
gdi32-sys = "0.1"
user32-sys = "~0.1.2"
kernel32-sys = "0.2"
dwmapi-sys = "0.1"

[target.'cfg(any(target_os = "linux", target_os = "dragonfly", target_os = "freebsd", target_os = "openbsd"))'.dependencies]
wayland-client = { version = "0.7.4", features = ["dlopen"] }
wayland-kbd = "0.6.2"
wayland-window = "0.4.2"
x11-dl = "2.8"
